### ISSUE TITLE
About qhull's version

### ISSUE THREAD

**Issue by axhiao** [qhull/qhull#1]
what is the difference between the current version of qhull on the github and that on the gitorious, especiall for qhull's c++ interface? If there are some diffs, i hope there will be a doc to illustrate it. Thanks:)

**Comment by qhull** [comment]
Hi Minglei,

gitorious closed down and is no longer 
available.  The 2012 commit (Qhull 2012.1) is the 
same as Gitorious and www.qhull.com/download.

The HEAD version is qhull 2015.0.2.  This is a 
prerelease of Qhull 2015.1 before it goes on the web.  Comments are welcome.

libqhull is substantially the same as 
before.  Identifiers for vertices and ridges are 32-bits.

libqhull_r is a redesign of Qhull for reentrant 
code.   Almost every procedure takes a qhT* 
parameter.   This allows multiple instances of Qhull to run at once.

The C++ interface was converted to 
libqhull_r.  The Gitorious version used 
qh_QHpointer, a clumsy way to swap between 
instances of Qhull.   There were many changes 
inside the classes, but the API is largely the same.

Compare the old and new user_eg3_r.cpp or the old and new qhulltest programs.

Old user_eg3
    RboxPoints rbox
    rbox.appendPoints("100");
    Qhull qhull;
    qhull.runQhull(rbox,"");

New user_eg3
    RboxPoints rbox("100");
    Qhull q(rbox, "")

src/Changes.txt lists all the changes.  See 
html/qh-code.htm for highlights (needs work).

                                 --Brad

At 04:20 AM 9/1/2015, Minglei Yin wrote:
