### ISSUE TITLE
Download issues, checksums do not match

### ISSUE THREAD

**Issue by neuhaus** [qhull/qhull#100]
Hello,

I had issues downloading qhull-2020.2 8.0.2 from the homepage (which lacks HTTPS 😨 ). I kept getting connection reset.

I then found the download for 2020.2 8.0.2 on github in the releases section and downloaded that instead.

I checked the MD5 checksums provided on qhull.org (URL http://www.qhull.org/download/qhull-2020-src-8.0.2-tgz.md5sum ) against the files in the tarball downloaded from github (URL https://github.com/qhull/qhull/archive/refs/tags/v8.0.2.tar.gz )

**They differ ❗**  

See [qhull.txt](https://github.com/qhull/qhull/files/7303156/qhull.txt)

What's up with that? Also, _please_ turn on HTTPS on qhull.org

**Comment by cbbarber** [comment]
Hi Sven,

The download page is the official release of Qhull.  The md5sum document refers to these downloads.   Disk was filled up accidently last week which may explain your access problems.
         http://www.qhull.org/download

The github tarballs are produced by github.   They have a different md5sum.

https for qhull.org is planned for the next release of qhull.

                        --Brad

**Comment by cbbarber** [comment]
Which files have different checksums?   Perhaps there's a misplaced use of CRLF.
