### ISSUE TITLE
Algorithm for generating facets

### ISSUE THREAD

**Issue by Zvyozdo4ka** [qhull/qhull#104]
It is written that "Qhull is a general dimension code for computing convex hull". Does it mean if I have as input 10 mln points, it would create facets from this points? Is it possible by using your library? And what kind of algorithm are you using for generating convex hull? Does it just connect all points?

**Comment by cbbarber** [comment]
Hi Julianna,

"General Dimension" means that Qhull works for 2-d, 3-d, 4-d, etc. data.   It is not tied to a specific dimension.

For introductions to convex hull and Qhull's algorithm, see http://www.qhull.org

The convex hull of 10 million random points in a 3-D cube produced 465 facets and 267 vertices.   For cospherical points, the number of facets increases rapidly with dimension.

                                                --Brad

**Comment by Zvyozdo4ka** [comment]
@cbbarber I appreciate your answer. But how did you get the number of facets and vertices? Is it constant? I thought it would depend on positions of dots.
