### ISSUE TITLE
Qhull 2020

### ISSUE THREAD

**Issue by stla** [qhull/qhull#108]
Hello,
 
  About three or four years ago, I wrapped Qhull in a [Haskell library](https://github.com/stla/qhull). Currently I'm wrapping it in R now. I've just seen that there was an update in 2020, but I didn't find any "changelog" file. Are there been important changes? Do you recommend to upgrade? Does my old code will work with the new version?

**Comment by davidcsterratt** [comment]
Re the R library, are you aware of the [R geometry package](https://davidcsterratt.github.io/geometry/), which already wraps qhull?  I'm the maintainer, and I'd welcome help with [issues](https://github.com/davidcsterratt/geometry/issues) or if you have ideas about refactoring the code.

**Comment by stla** [comment]
Hello,

  Yes I know your package. I'm also the author of [cxhull](https://github.com/stla/cxhull). The **cxhull** package only allows to get the convex hull but I think it provides more information than the **geometry** convex hull. For example I can do [that](https://laustep.github.io/stlahblog/frames/rgl_truncTesseract2.html) and [that](https://gist.githubusercontent.com/stla/83925fce019921ec12440ad05fdcd213/raw/839458ffc08d4d07ff6c4775c405fa3683866738/RTT.gif) with **cxhull**. Now I'm working on the [tessellation](https://github.com/stla/tessellation) package, which allows to get Delaunay and Voronoï tessellations. As you can see in the README, we can get funny Voronoï cells/diagrams. I'm not a star in C nor in C++, and I almost don't understand anymore my code (produced more than 3 years ago). Not sure I can help.

**Comment by cbbarber** [comment]
The change log is in the src directory.  See the Wiki for changes
   https://github.com/qhull/qhull/blob/master/src/Changes.txt

8.1_alpha1 fixed a message for reporting an error.
