### ISSUE TITLE
Broken url

### ISSUE THREAD

**Issue by giumas** [qhull/qhull#12]
This url returns a 404 page: https://github.com/qhull/qhull/blob/master/Announce.txt#L28
![chrome_2016-06-21_09-59-49](https://cloud.githubusercontent.com/assets/2849257/16232106/4474bf12-3797-11e6-8513-eae23c0f6e6a.png)

Possible substitute: http://dl.acm.org/citation.cfm?id=235821

**Comment by cbbarber** [comment]
Fixed.
