### ISSUE TITLE
Missing examples in the CMake file

### ISSUE THREAD

**Issue by giumas** [qhull/qhull#13]
I have found the examples ``user_eg1``, ``user_eg2`` and ``user_eg3`` helpful to understand how to interact with the library. And I have noticed them thanks to this [SO]( http://stackoverflow.com/questions/29156437/provide-qconvexs-input-in-c-code).

Why are they missing from the CMake file?

**Comment by qhull** [comment]
They remain in the CMakeLists.txt file.  The 
source file is user_eg_r.c instead of 
user_eg.c.  Users of Qhull should switch to the 
reentrant library for their code.

e.g., line 528
set(user_eg_SOURCES     src/user_eg/user_eg_r.c)

                                 --Brad

At 01:59 PM 6/21/2016, you wrote:
