### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by amodregob** [qhull/qhull#132]
I have been trying to download QHull and the link given by the error is not working. The link is the following:
www.qhull.org/download/qhull-2020-src-8.0.2.tgz

**Comment by Jacob-Stevens-Haas** [comment]
Same issue, but not via browser.

When trying to set up a dev environment for matplotlib, their meson build backend downloads and builds freetype and qhull.  It completes freetype, but on qhull it receives connection reset:

```
      Downloading qhull source from http://www.qhull.org/download/qhull-2020-src-8.0.2.tgz
      WARNING: failed to download with error: [Errno 104] Connection reset by peer. Trying after a delay...
      WARNING: failed to download with error: [Errno 104] Connection reset by peer. Trying after a delay...
      WARNING: failed to download with error: [Errno 104] Connection reset by peer. Trying after a delay...
```

**Comment by Jacob-Stevens-Haas** [comment]
Additionally both wget and python requests fail to download this file.  It appears wget hits a byte read error about 35-38% through (e.g. bye 499035 of 1298874), tries to request the rest in a new connection, and gets a "416 Range Not Satisfiable" response.

```
(env) xenophon@pontus:~/github/matplotlib$ wget -v http://www.qhull.org/download/qhull-2020-src-8.0.2.tgz
--2023-10-23 11:26:20--  http://www.qhull.org/download/qhull-2020-src-8.0.2.tgz
Resolving www.qhull.org (www.qhull.org)... 64.71.34.21
Connecting to www.qhull.org (www.qhull.org)|64.71.34.21|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1298874 (1.2M) [application/x-gzip]
Saving to: ‘qhull-2020-src-8.0.2.tgz’

qhull-2020-src-8.0.2.tgz                            35%[======================================>                                                                          ] 444.57K   564KB/s    in 0.8s    

2023-10-23 11:26:22 (564 KB/s) - Read error at byte 455235/1298874 (Connection reset by peer). Retrying.

--2023-10-23 11:26:23--  (try: 2)  http://www.qhull.org/download/qhull-2020-src-8.0.2.tgz
Connecting to www.qhull.org (www.qhull.org)|64.71.34.21|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.
```

**Comment by cbbarber** [comment]
This looks like an incompatibility between your environment and the Qhull server.   I have no problem with downloading the file.   I have not heard of download issues from others.

Perhaps you are configured for concurrent download links and qhull.org does not support Range requests.

**Comment by Jacob-Stevens-Haas** [comment]
It works now - it was just down for a few days for me.

**Comment by Jacob-Stevens-Haas** [comment]
Heads up - rediscovered the issue.  The problem is that many corporate/academic networks block downloading tarballs using non-secure HTTP.  The workaround is to use the tarball on github.
