### ISSUE TITLE
Typos in the "qconvex outputs" part of the Qhull manual

### ISSUE THREAD

**Issue by beijiguang94** [qhull/qhull#134]
In the "qconvex outputs" part of the Qhull manual on this [website](http://www.qhull.org/html/qconvex.htm), for the "o" option, it reads 

> print vertices and facets of the convex hull in OFF format. The first line is the dimension. The second line is the number of vertices, facets, and ridges. The vertex coordinates are next, followed by the facets. Each facet starts with the number of vertices...

However, the "o" option actually prints the (input) points and facets of the convex hull in OFF format. Thus, the above quote should be

> print points and facets of the convex hull in OFF format. The first line is the dimension. The second line is the number of points, facets, and ridges. The point coordinates are next, followed by the facets. Each facet starts with the number of vertices...

**Comment by cbbarber** [comment]
Good catch.   Thanks for the corrected entry.

The same problem occurs for qhalf documentation.
  http://www.qhull.org/html/qhalf.htm#outputs

The 'o' documentation is correct.
   http://www.qhull.org/html/qh-opto.htm#o

Both problems will be fixed in the next full release.

**Comment by beijiguang94** [comment]
> Good catch.   Thanks for the corrected entry.
> 
> The same problem occurs for qhalf documentation.
>   http://www.qhull.org/html/qhalf.htm#outputs
> 
> The 'o' documentation is correct.
>    http://www.qhull.org/html/qh-opto.htm#o
> 
> Both problems will be fixed in the next full release.

Nice. Thanks for your efforts.
