### ISSUE TITLE
Is the Qhull library able to run on Android phones? 

### ISSUE THREAD

**Issue by QQHEZhangyubin** [qhull/qhull#135]
Is the Qhull library able to run on Android phones? I tried to run this project in my Android project, but the QHULL_LIB_CHECK in the orgQhull::Qhull constructor always reports an error and exits the application. In addition, in the destructor of orgQhull::Qhull, it also throws QhullError(10026, "Qhull error: qhull did not free %d bytes of long memory (%d pieces).", totlong, curlong); I suspect that this project cannot be ported to the Android system. I wonder if my suspicion is correct, looking forward to your answer.

**Comment by cbbarber** [comment]
It should be able to run on any system that can compile the code.  QHULL_LIB_CHECK is probably correct in reporting the error.  Something may be wrong with your build.  You can also build Qhull statically without using a shared library.

**Comment by QQHEZhangyubin** [comment]
> It should be able to run on any system that can compile the code. QHULL_LIB_CHECK is probably correct in reporting the error. Something may be wrong with your build. You can also build Qhull statically without using a shared library.

Yes, it's my issue. According to macro definition, I want to use a thread-safe static library, but I linked a non-thread-safe library, which caused the verification to fail in the constructor.
