### ISSUE TITLE
qh_version and qh_version2 not properly exported on Windows

### ISSUE THREAD

**Issue by brechtsanders** [qhull/qhull#139]
I'm on Windows using MinGW-w64 GCC compiler (using MSYS2 shell)

I had issues when gr-c tried to detect the version of the installed qhull.

It turns out these are variables that were not exported as DATA in the `.def` files.

Eferything works fine after I rebuilt qhull 2020.2 with the following fix:

I added ` DATA` after `qh_version` and `qh_version2` in `*/*/*.def`.

**Comment by cbbarber** [comment]
Will do soon.

**Comment by cbbarber** [comment]
Added DATA after qh_version and qh_version2.  Other symbols are CODE

**Comment by cbbarber** [comment]
Closed with tag 8.1-alpha4
