### ISSUE TITLE
Missing release tag

### ISSUE THREAD

**Issue by albamath** [qhull/qhull#14]
Hi, please could you add release tags every time a new release is there.

For example, it seems that the latest revision for Qhull 2015.2 is the commit [5a79a0009454c86e9848646b3c296009125231bf](https://github.com/qhull/qhull/tree/5a79a0009454c86e9848646b3c296009125231bf) on 19 Jan, it would have been easier to find if it has been tagged.

Best regards

**Comment by qhull** [comment]
Good idea (I'm not a regular git user).   They're on the to-do list.

Thanks for your suggestion.

                         --Brad

At 05:04 AM 7/5/2016, Alba MÃ¡laga wrote:

**Comment by dcompgriff** [comment]
2 years and still no tags.... this should be an easy fix. Without tags, you have to go through other sources to download the specific version of qhull that you want.

**Comment by qhull** [comment]
Thanks for the prompt.   In the next couple of weeks I'll start working on Qhull.   Release tags are a good idea.  I'll add them first.

                                --Brad

At 10:35 AM 9/13/2018, dcompgriff wrote:

**Comment by cbbarber** [comment]
All set.  Tags have been added with the Unix version numbers and Year-release numbers.
