### ISSUE TITLE
Installing doesn't install bins or libs

### ISSUE THREAD

**Issue by sbojarovski** [qhull/qhull#15]
Hi,

I'm building on Windows 7, with Visual Studio 2013, and Cmake  3.0.2

Cmake creates a solution, and then I am able to build it with VS 2013 (both Debug and Release) without any errors.

However, when I build the `INSTALL` project in VS 2013 (in order to copy the files to the install location), only the documentation and the include files are copied.

The binaries and libraries are not, and no `bin` or `lib` folder is created.

By looking at `CmakeLists.txt`, this line should be the faulty one:

```
install(TARGETS ${qhull_TARGETS_INSTALL}
        RUNTIME DESTINATION ${BIN_INSTALL_DIR}
        LIBRARY DESTINATION ${LIB_INSTALL_DIR}
        ARCHIVE DESTINATION ${LIB_INSTALL_DIR})
```

but I don't know how to fix it.

Any help would be appreciated.

Best regards,
Stefan

**Comment by qhull** [comment]
At 06:08 AM 7/11/2016, sbojarovski wrote:

>Hi,
>
>I'm building on Windows 7, with Visual Studio 2013, and Cmake 3.0.2

The 'zip' distribution of Qhull includes VS 
project files.  They are generated 
post-processing the CMake build (see 
eg/make-vcproj.sh).  My memory was that the 
INSTALL target didn't work well, so I didn't 
include it.   The project files are XML and 
fairly straightforward to reverse engineer.   If 
you figure out a better way, you could request an 
update to the CMake template for Visual Studio.

                                 --Brad

**Comment by haudren** [comment]
Actually, the problem is that `qhull_INSTALL_TARGETS` is not automatically defined.

Thus, applying this patch:
```diff
-install(TARGETS ${qhull_TARGETS_INSTALL}
+install(TARGETS ${qhull_STATIC} ${qhull_STATICR} qhull rbox qconvex qdelaunay qvoronoi qhalf
         RUNTIME DESTINATION ${BIN_INSTALL_DIR}
         LIBRARY DESTINATION ${LIB_INSTALL_DIR}
         ARCHIVE DESTINATION ${LIB_INSTALL_DIR})
```
Solves the problem. Another option is to populate the list `qhull_TARGETS_INSTALL` by hand. If you have any preference, I can submit an actual pull request.

**Comment by qhull** [comment]
Thanks Herve for your notes.

The jun'16 commit for CMakelists.txt is 
incorrect.  The previous commit (Qhull 2015.2) 
includes qhull_TARGETS_INSTALL.   I'm reviewing 
it soon as part of the next release.

I'll review your comments then.

                                 --Brad

At 11:03 PM 3/13/2017, you wrote:

**Comment by cbbarber** [comment]
Reverted the jun'16 change to CMakeList.txt which had deleted 200 lines, including qhull_TARGETS_INSTALL

I'm sorry it took so long.  I've returned to Qhull work.
