### ISSUE TITLE
qhull compilation fails to compile witn Intel Compiler / Linux

### ISSUE THREAD

**Issue by nine7nine** [qhull/qhull#16]
hi,

I bumped into a build failure using the Intel Compiler and qhull on Archlinux 64bit. I had initially tried to compile CloudCompare, which uses an older version of qhull - which failed. Then I decided to give the current qhull_r a try (which I compiled on it's own) and bumped into the same issue;

[ 44%] Building CXX object CMakeFiles/qhullcpp.dir/src/libqhullcpp/Coordinates.cpp.o
In file included from /home/ninez/pkgs/Icc/qhull/src/qhull-2015.2/src/libqhullcpp/Coordinates.h(13),
                 from /home/ninez/pkgs/Icc/qhull/src/qhull-2015.2/src/libqhullcpp/Coordinates.cpp(9):
/home/ninez/pkgs/Icc/qhull/src/qhull-2015.2/src/libqhull_r/qhull_ra.h(105): error: this declaration may not have extern "C" linkage
  template <typename T>
  ^

compilation aborted for /home/ninez/pkgs/Icc/qhull/src/qhull-2015.2/src/libqhullcpp/Coordinates.cpp (code 2)
make[2]: **\* [CMakeFiles/qhullcpp.dir/build.make:63: CMakeFiles/qhullcpp.dir/src/libqhullcpp/Coordinates.cpp.o] Error 2
make[1]: **\* [CMakeFiles/Makefile2:216: CMakeFiles/qhullcpp.dir/all] Error 2
make: **\* [Makefile:139: all] Error 2

Intel Compier version; icc -V

Intel(R) C Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 17.0.0.098 Build 20160721 Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.
FOR NON-COMMERCIAL USE ONLY

qhull_ra.h seems to have this line defined FOR the Intel Compiler / on a non-windows version;
# if defined(__cplusplus) && defined(__INTEL_COMPILER) && !defined(QHULL_OS_WIN)

but it doesn't seem to be working over here. Just thought I would point it out.

thanks!

**Comment by nine7nine** [comment]
after removing;

-#if defined(__cplusplus) && defined(__INTEL_COMPILER) && !defined(QHULL_OS_WIN)
-template <typename T>
-inline void qhullUnused(T &x) { (void)x; }
-#  define QHULL_UNUSED(x) qhullUnused(x);
-#else
-#  define QHULL_UNUSED(x) (void)x;
-#endif

and all references to QHULL_UNUSED from the sources, ICC can compile qhull. patch; http://pastebin.com/Pq5DtqKA ... That being said; I haven't tested the latest qhull, beyond patching it to get it to compile. 

However, I have tested the older/deprecated libqhull used in CloudCompare by their QHPR plugin, which works. In the old libqhull, I only needed to patch qhull_a.h && io.c; http://pastebin.com/L3QuAmpN

**Comment by nine7nine** [comment]
I ended up forking this repo to add the patch(es) to remove the QHULL_UNUSED stuff; 

https://github.com/nine7nine/qhull/commits/master

the first commit removes the code to get it to compile on Archlinux with ICC. The next commit removes the comments, html ref. and removes one last QHULL_UNUSED in user_eg2.c, which I never accounted for (or bumped into compiling libqhull or liobqhull_r). thx

**Comment by cbbarber** [comment]
Fixed in Qhull 2018.0.1.   Qhull 2019.1 will be released later this month.

 - Move 'extern "C" {}' logic from C++ to C headers [C. Atkins, nine7nine, wscullin, alalazo]

**Comment by cbbarber** [comment]
Two problems were reported.   'extern' was fixed but 'QHULL_UNUSED' remains a specified above.

Is this definition incorrect?   It was based on the Q_UNUSED macro from Qt (corelib/global/qglobal.h).

I need someway to mark expected, but unused, variables due to various #option settings.

**Comment by cbbarber** [comment]
Does the Intel compiler work OK for Qhull 2019.1 on Archlinux 64bit?   If so, please close this issue.

**Comment by cbbarber** [comment]
Please reopen if QHULL_UNUSED remains an issue
