### ISSUE TITLE
Likely accidental zero'ification of variable

### ISSUE THREAD

**Issue by rouault** [qhull/qhull#17]
Found by Coverity Scan on the internal libqhull in GDAL

At https://github.com/qhull/qhull/blob/master/src/libqhull/io.c#L429, there's :

```
if (angle < 0)
   angle -= angle;
```

This results in zero'ifying the variable, whereas changing its sign was probably intended.

**Comment by cbbarber** [comment]
Good catch.   It should indeed be angle= -angle.   This statement is used for the Wridgeok and Wridge0 statistics.   It does not otherwise contribute to the results.  

The same change is also needed for io_r.c
