### ISSUE TITLE
CMake: using qhull as external project

### ISSUE THREAD

**Issue by GPMueller** [qhull/qhull#18]
I'm having trouble using qhull as an external Project via CMake. It always builds everything but installs nothing unless specified. But specifying `-Dqhull_TARGETS_INSTALL=qhullstatic_r;qhullcpp` will unfortunately not work.

It seems currently the only way to use the qhullcpp library as an external Project is:

    include(ExternalProject)
    ExternalProject_add(qhullstatic_r
    	SOURCE_DIR    "${CMAKE_SOURCE_DIR}/thirdparty/qhull"
    	# GIT_REPOSITORY https://github.com/qhull/qhull
    	CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR}/thirdparty-install;-Dqhull_TARGETS_INSTALL=qhullstatic_r"
    	PREFIX qhull-prefix
    )
    
    ExternalProject_add(qhullcpp
    	SOURCE_DIR    "${CMAKE_SOURCE_DIR}/thirdparty/qhull"
    	# GIT_REPOSITORY https://github.com/qhull/qhull
    	CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR}/thirdparty-install;-Dqhull_TARGETS_INSTALL=qhullcpp"
    	PREFIX qhull-prefix
    	DEPENDS qhullstatic_r
    )
    
    add_library(libqhullstatic_r STATIC IMPORTED)
    set_property(TARGET libqhullstatic_r PROPERTY IMPORTED_LOCATION ${PROJECT_BINARY_DIR}/thirdparty-install/lib/${CMAKE_STATIC_LIBRARY_PREFIX}qhullstatic_r${CMAKE_STATIC_LIBRARY_SUFFIX})
    add_dependencies(libqhullstatic_r qhullstatic_r)

    add_library(libqhullcpp STATIC IMPORTED)
    set_property(TARGET libqhullcpp PROPERTY IMPORTED_LOCATION ${PROJECT_BINARY_DIR}/thirdparty-install/lib/${CMAKE_STATIC_LIBRARY_PREFIX}qhullcpp${CMAKE_STATIC_LIBRARY_SUFFIX})
    set_property(TARGET libqhullcpp PROPERTY INTERFACE_LINK_LIBRARIES libqhullstatic_r)
    add_dependencies(libqhullcpp qhullcpp)

Is this by design or might it be improved?

**Comment by GPMueller** [comment]
I would also like to know if it is by design that as a default, **no library is installed, unless the install target is passed**.

It is possible to circumvent the above problem, but one then has to reference the qhull build directory (install directory would be a cleaner approach):

    include(ExternalProject)
    ExternalProject_add(qhull
	    SOURCE_DIR    "${CMAKE_SOURCE_DIR}/thirdparty/qhull"
	    # GIT_REPOSITORY https://github.com/qhull/qhull.git
	    BINARY_DIR ${CMAKE_BINARY_DIR}/thirdparty-build/qhull
	    # INSTALL_DIR ${CMAKE_BINARY_DIR}/thirdparty-install
	    CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/thirdparty-install"
	    CMAKE_CACHE_ARGS "-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true"
    )
    ### qhullstatic reentrant library
    add_library(libqhullstatic_r STATIC IMPORTED)
    set_property(TARGET libqhullstatic_r PROPERTY IMPORTED_LOCATION ${CMAKE_BINARY_DIR}/thirdparty-build/qhull/${CMAKE_STATIC_LIBRARY_PREFIX}qhullstatic_r${CMAKE_STATIC_LIBRARY_SUFFIX})
    set_property(TARGET libqhullstatic_r PROPERTY IMPORTED_LOCATION_DEBUG ${CMAKE_BINARY_DIR}/thirdparty-build/qhull/Debug/${CMAKE_STATIC_LIBRARY_PREFIX}qhullstatic_r${CMAKE_STATIC_LIBRARY_SUFFIX})
    set_property(TARGET libqhullstatic_r PROPERTY IMPORTED_LOCATION_RELEASE ${CMAKE_BINARY_DIR}/thirdparty-build/qhull/Release/${CMAKE_STATIC_LIBRARY_PREFIX}qhullstatic_r${CMAKE_STATIC_LIBRARY_SUFFIX})
    add_dependencies(libqhullstatic_r qhull)
    ### qhullcpp library
    add_library(libqhullcpp STATIC IMPORTED)
    set_property(TARGET libqhullcpp PROPERTY IMPORTED_LOCATION ${CMAKE_BINARY_DIR}/thirdparty-build/qhull/${CMAKE_STATIC_LIBRARY_PREFIX}qhullcpp${CMAKE_STATIC_LIBRARY_SUFFIX})
    set_property(TARGET libqhullcpp PROPERTY IMPORTED_LOCATION_DEBUG ${CMAKE_BINARY_DIR}/thirdparty-build/qhull/Debug/${CMAKE_STATIC_LIBRARY_PREFIX}qhullcpp${CMAKE_STATIC_LIBRARY_SUFFIX})
    set_property(TARGET libqhullcpp PROPERTY IMPORTED_LOCATION_RELEASE ${CMAKE_BINARY_DIR}/thirdparty-build/qhull/Release/${CMAKE_STATIC_LIBRARY_PREFIX}qhullcpp${CMAKE_STATIC_LIBRARY_SUFFIX})
    set_property(TARGET libqhullcpp PROPERTY INTERFACE_LINK_LIBRARIES libqhullstatic_r)
    add_dependencies(libqhullcpp qhull)

**Comment by cbbarber** [comment]
200 lines were accidentally deleted from CMakeLists.txt.   The file has been restored. 

                                         --Brad
