### ISSUE TITLE
Add pkg-config support

### ISSUE THREAD

**Issue by haudren** [qhull/qhull#22]
For Linux users it would be valuable to provide a `qhull.pc` file. This allows for a standardized way of figuring out the location of `qhull` on the system. This configuration file is generated at configuration (i.e. during cmake runs) time. Note that `pkg-config` can also be used under Windows, and helps to find packages installed in non-standard locations.

I can send a PR if there is interest in this feature.

**Comment by heroxbd** [comment]
I can see a qhull.pc.in template in the git repo.  But it is not released in the tarball.

**Comment by qhull** [comment]
Yes.  Someone checked in qhull.pc.in.   It's for 
an older version for Qhull.   Qhull contains 
several builds so I didn't know how to set this 
file.  I'm not a pkg-config user.  It looks like it is for the 'qhull' program.

Compiled builds should use the reentrant library for qhull (qhull_r).

Please submit an updated version of qhull.pc.in 
for qhull 2015.2.  It was built with reentrant 
library.  I'll add the file to the next release 
of Qhull (late this year or early next year).

                         --Brad


At 11:19 PM 7/8/2017, you wrote:

**Comment by cbbarber** [comment]
Removed qhull.pc.in
