### ISSUE TITLE
qhull.org website is defaced

### ISSUE THREAD

**Issue by thecount2a** [qhull/qhull#29]
It looks like the qhull.org website is defaced and is hosting pages that redirect to Viagra sales websites.  Use the following google link to see that the viagra forwarding pages have been cached on google already: google.com/search?q=site:qhull.org+viagra

Can somebody on the team that is responsible be notified so that they can clean the server up and remove this from the webroot?  This will badly affect qhulls results on google as soon as they become associated with such content.

**Comment by cbbarber** [comment]
This appears to be a Google hack.  I've notified Google.

**Comment by thecount2a** [comment]
It turns out that the qhull.org website actually delivers a webpage for these previously defaced URLs. Can the qhull.org website be changed to reply a 404 not found page when an unknown URL is accessed?  Then google's search crawlers would automatically remove them from the google cache next time they crawl qhull.org.
