### ISSUE TITLE
Installation make

### ISSUE THREAD

**Issue by asekez** [qhull/qhull#3]
Hey, 
I want to use qhull in a C++ program; thus I wanted to build Qhull, static libraries, shared library, and C++ interface with gcc. However I got this error message : 

make: *** No rule to make target `src/libqhull/usermem_r.o', needed by `bin/testqset_r'.  Stop.

Thank you,

**Comment by asekez** [comment]
There is a typo in the Makefile at line 662 : replace "src/libqhull/usermem_r.o" with "src/libqhull_r/usermem_r.o"

**Comment by qhull** [comment]
Good catch.    I've updated Makefile

                                       --Brad
