### ISSUE TITLE
 -Wstringop-truncation Warning

### ISSUE THREAD

**Issue by davidcsterratt** [qhull/qhull#37]
When running checks on the R geometry package using gcc-8 with `-Wall` I got the following error:
```
rboxlib_r.c:358:5: warning: ‘strncat’ output may be truncated copying between 0 and 199 bytes from a string of length 199   [-Wstringop-truncation]
     strncat(command, seedbuf, sizeof(command)-strlen(command)-1);     
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
See https://github.com/davidcsterratt/geometry/issues/31

**Comment by cbbarber** [comment]
Thanks David for resolving this warning.  I couldn't make sense of it.   See my change notes to your pull request.
