### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by marcos-sandim** [qhull/qhull#4]
Hi, I'm using MSVC 2012 and having some issues with memory leaks.
I'm using the C++ Interface (qhullcpp  and libqhullstatic_r) to compute convex hulls from my application.
The example user_eg3_r.cpp also have these leaks.
Are you working on it or have any advice for me to try to fix it?

Thanks.

**Comment by qhull** [comment]
At 05:17 PM 12/9/2015, you wrote:

>Hi, I'm using MSVC 2012 and having some issues with memory leaks.

I'm not aware of the memory leaks.  Please send 
me the call for user_eg3_r.cpp with evidence of a 
memory leak.  If you use option 'T5' memory allocations are logged.

                                 --Brad

**Comment by marcos-sandim** [comment]
In MSVC 2012 I followed the instructions in https://msdn.microsoft.com/en-us/library/x98tx3cf%28v=vs.110%29.aspx to check for leaks, which resulted in:

> 'user_eg3.exe' (Win32): Loaded 'D:\Code\qhull\bin\user_eg3.exe'. Symbols loaded.
> 'user_eg3.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
> 'user_eg3.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
> 'user_eg3.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
> 'user_eg3.exe' (Win32): Loaded 'C:\Windows\System32\msvcp110d.dll'. Symbols loaded.
> 'user_eg3.exe' (Win32): Loaded 'C:\Windows\System32\msvcr110d.dll'. Symbols loaded.
> The thread 0x26a0 has exited with code 0 (0x0).
> The thread 0x1794 has exited with code 0 (0x0).
> The thread 0x27f0 has exited with code 0 (0x0).
> Detected memory leaks!
> Dumping objects ->
> {176} normal block at 0x000000F895EC5160, 131072 bytes long.
>  Data: <        hS      > 00 00 00 00 00 00 00 00 68 53 EC 95 F8 00 00 00 
> {175} normal block at 0x000000F895EC4F10, 484 bytes long.
>  Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> {174} normal block at 0x000000F895EC4E10, 144 bytes long.
>  Data: < R       S      > D0 52 EC 95 F8 00 00 00 E0 53 EC 95 F8 00 00 00 
> {173} normal block at 0x000000F895EC4D60, 72 bytes long.
>  Data: <        (   0   > 18 00 00 00 20 00 00 00 28 00 00 00 30 00 00 00 
> Object dump complete.
> The program '[9808] user_eg3.exe' has exited with code 0 (0x0).

Valgrind also found leaks (Fedora 22, gcc 5.1.1):

> ==6396== Memcheck, a memory error detector
> ==6396== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
> ==6396== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
> ==6396== Command: ./user_eg3 eg-100
> ==6396==
> 
> (./user_eg3 eg-100 output...)
> 
> ==6396==
> ==6396== HEAP SUMMARY:
> ==6396==     in use at exit: 204,476 bytes in 5 blocks
> ==6396==   total heap usage: 56 allocs, 51 frees, 234,741 bytes allocated
> ==6396==
> ==6396== LEAK SUMMARY:
> ==6396==    definitely lost: 700 bytes in 3 blocks
> ==6396==    indirectly lost: 131,072 bytes in 1 blocks
> ==6396==      possibly lost: 0 bytes in 0 blocks
> ==6396==    still reachable: 72,704 bytes in 1 blocks
> ==6396==         suppressed: 0 bytes in 0 blocks
> ==6396== Rerun with --leak-check=full to see details of leaked memory
> ==6396==
> ==6396== For counts of detected and suppressed errors, rerun with: -v
> ==6396== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

Hope this helps.

**Comment by qhull** [comment]
The leak is probably in the C++ classes, perhaps a destructor that is not cleaning up.  It may be the Qhull object.   If you can identify the leaked data, let me know.

**Comment by qhull** [comment]
Many thanks for reporting this issue and MSVC's memory leak detector.   Support for _CRTDBG_MAP_ALLOC was added to user_r.h and qh_lib_check().   Include files were rearranged to allow QHULL_CRTDBG for all programs.   Other memory leaks were found as well as missing calls to free memory under error conditions.   See Changes.txt.

Qhull 2012.2 fixes these issues.
