### ISSUE TITLE
Software license unclear?

### ISSUE THREAD

**Issue by 130s** [qhull/qhull#40]
Thank you for the great tool!

Neither http://www.qhull.org/COPYING.txt nor [github.com/qhull/qhull/COPYING.txt](https://github.com/qhull/qhull/blob/a0e0374a7f67efe7f5ec196417843a60e9f7b761/COPYING.txt) don't seem to declare license for your software. What license is qhull is opensource under, and would you clarify it somewhere?

**Comment by cbbarber** [comment]
Hi Isaac,

Qhull was licensed before the consolidation of open source license agreements.

COPYING.txt is the Qhull license.   It is permissive, as long as you maintain the copyright notices and include COPYING.txt. 

Citing Qhull in your publications is appreciated.  See REGISTER.txt.

                                --Brad

At 03:45 PM 03/06/2019, Isaac I.Y. Saito wrote:
