### ISSUE TITLE
Finding Hulls in embedded spaces

### ISSUE THREAD

**Issue by infophysics** [qhull/qhull#41]
I'm currently trying to find convex hulls for a small number of points in a potentially large dimension.  The issue I'm having is that, the points themselves are not necessarily in general position, so they do not represent a polytope of the dimension they live in.  For example, I could have a set of points that all lie on a line, but are given by a set of four coordinates embedded in 4D.  I would still like qhull to tell me that the convex hull is the line connected the two extreme points, however it will not do this.  

Is there are way to force qhull to do this as it stands or does it require a completely new set of tools to be written?

**Comment by cbbarber** [comment]
Qhull's error message on low-dimensional data provides the evidence and offers several suggestions for handling the data.    

See below for points on a 3-d line

                        --Brad



rbox P1.0 P0.0 P2.0 P3.0
3 rbox P1.0 P0.0 P2.0 P3.0
4
     1      0      0
     0      0      0
     2      0      0
     3      0      0


rbox P1.0 P0.0 P2.0 P3.0 | qhull
QH6154 Qhull precision error: Initial simplex is flat (facet 1 is coplanar with the interior point)

While executing: rbox P1.0 P0.0 P2.0 P3.0 | qhull
Options selected for Qhull 2018.0.1.r 2018/12/28:
  run-id 1390226823  _pre-merge  _zero-centrum  _max-width  3
  Error-roundoff 2.7e-015  _one-merge 1.9e-014  _near-inside 9.4e-014
  Visible-distance 5.4e-015  U-max-coplanar 5.4e-015  Width-outside 1.1e-014
  _wide-facet 3.2e-014  _maxoutside 2.1e-014

      5 zero divisors during back substitute

The input to qhull appears to be less than 3 dimensional, or a
computation has overflowed.

Qhull could not construct a clearly convex simplex from points:
- p2(v3):     2     0     0
- p0(v2):     1     0     0
- p3(v1):     3     0     0
- p1(v0):     0     0     0

The center point is coplanar with a facet, or a vertex is coplanar
with a neighboring facet.  The maximum round off error for
computing distances is 2.7e-015.  The center point, facets and distances
to the center point are as follows:

center point      1.5        0        0

facet p0 p3 p1 distance=    0
facet p2 p3 p1 distance=    0
facet p2 p0 p1 distance=    0
facet p2 p0 p3 distance=    0

These points either have a maximum or minimum x-coordinate, or
they maximize the determinant for k coordinates.  Trial points
are first selected from points that maximize a coordinate.

The min and max coordinates for each dimension are:
  0:         0         3  difference=    3
  1:         0         0  difference=    0
  2:         0         0  difference=    0

If the input should be full dimensional, you have several options that
may determine an initial simplex:
  - use 'QJ'  to joggle the input and make it full dimensional
  - use 'QbB' to scale the points to the unit cube
  - use 'QR0' to randomly rotate the input for different maximum points
  - use 'Qs'  to search all points for the initial simplex
  - use 'En'  to specify a maximum roundoff error less than 2.7e-015.
  - trace execution with 'T3' to see the determinant for each point.

If the input is lower dimensional:
  - use 'QJ' to joggle the input and make it full dimensional
  - use 'Qbk:0Bk:0' to delete coordinate k from the input.  You should
    pick the coordinate with the least range.  The hull will have the
    correct topology.
  - determine the flat containing the points, rotate the points
    into a coordinate plane, and delete the other coordinates.
  - add one or more points to make the input full dimensional.


At 08:17 PM 03/27/2019, Nicholas Carrara wrote:

**Comment by cbbarber** [comment]
Closing.   

Qhull does not handle lower-dimensional data as is.   Perhaps the easiest approach is to add extra points to make the hull full-dimensional and then extract the lower-dimensional topology from the convex hull.

Other suggestions follow "you have several options" in the previous reply.
