### ISSUE TITLE
wrong convex hull reconstruction from the hyper planes returned by qhull

### ISSUE THREAD

**Issue by JianqiangDing** [qhull/qhull#44]
Hi, I'm doing some experiments with qhull to construct convex hull  from points (c++), the problem occurred when debugging my program, I just found I can not reconstruct the convex hull from hyperplanes returned by qhull
here is the function

	template <typename Number>
	std::vector<ratbox::HalfSpace<Number>> getHalfSpaces(const orgQhull::Qhull& qhull)
	{
		std::vector<ratbox::HalfSpace<Number>> retHalfSpaces;
		for (const orgQhull::QhullFacet& qhullFacet : qhull.facetList())
		{
			// retHalfSpaces.emplace_back(ratbox::HalfSpace<Number>(getNormal<Number>(qhullFacet.hyperplane()),
			// 													 getOffset<Number>(qhullFacet.hyperplane())));
			retHalfSpaces.emplace_back(ratbox::HalfSpace<Number>(getNormal<Number>(qhullFacet.hyperplane()),
																 getOffset<Number>(qhullFacet.hyperplane())));
		}
		return retHalfSpaces;
	}

so, is it wrong to call hyperplane() method?? or should I use an inner hyperplane or outer hyperplane?? or is there some operations else I haven't complete??

the algorithm I implemented to reconstruct the convex hull can be found in the link following:
https://ww2.mathworks.cn/matlabcentral/fileexchange/7894-con2vert-constraints-to-vertices
I just use this algorithm to get all the vertices and re-input them into qhull to construct the new convex hull, but it failed, there are some extremely strange points which coordinate are too close to the origin or too far away from the reasonable domain.

I've done some tests about the function conv2vert, the results are good, so I guess there may be some mistakes when using qhull?? can you help me to solve this problem??
any suggestion would be helpful

Best

**Comment by cbbarber** [comment]
Please review the error messages returned by Qhull.   Set the trace options via qhullCommand for Qhull::runQhull.   Option 'T4' gives a full trace.
    http://www.qhull.org/html/qh-optt.htm#trace

**Comment by JianqiangDing** [comment]
thanks for the really fast reply, but I do not think you may understand the problem right way, qhull does not throw out any kind of error message, it works fine, my question is, cause qhull only construct the convex hull from points, so I am trying to implement a method so that I can construct a convex hull from constraints like AX<=B, but it failed, qhull maintain three kinds of hyperplane, **what kind of the hyperplane is suitable for reconstruct the related convex hull? inner or outer or just hyperplane? and do you have any kind of suggestion about the method which can convert constraints AX<=B to a convex hull?**
the algorithm I mentioned above, is an algorithm that can enumerate extreme vertices through dual polytope computing, there would be some wrong points generated caused by linear system solving using Eigen, why don't you provide a similar method in qhull(from constraints to the convex hull)?
that's what I want, the qhull does not throw any kind of errors, it works fine.
here is the link about the algorithm:
https://stackoverflow.com/questions/26809630/how-to-convert-the-half-spaces-that-constitute-a-convex-hull-to-a-set-of-extreme

**Comment by JianqiangDing** [comment]
dear cbbarber, I've checked the document of qhull several times and write some tests, I just found all kinds of hyperplanes does not ensure hold all vertices inside?? I mean not always all hyperplane and all vertices returned by qhull satisfy AX+B<=0, I've checked the data, even it's really small, almost like  9.53674e-07, but it is still positive, why?? could you please help me resolve the problem?? how to make sure all the vertices and hyperplanes returned satisfy AX+B<=0. 
the problem troubled me no matter what kind of reconstructing method used, the result always wrong. 
do need help!

Best

**Comment by cbbarber** [comment]
My guess is that the distance test is incorrect or does not account for qh.DISTround.   For example code, see the exhaustive test of all points and all facets (qhull option 'Tv')

In poly2_r.c,
  qh_check_points
which calls
  qh_check_point 
which compares the computed distance to 'maxoutside'

qh_check_points defines 'maxoutside' for each facet
        maxoutside= facet->maxoutside + 2* qh->DISTround;
        /* one DISTround to actual point and another to computed point */

---------------

Regarding your previous questions --

Each constraint corresponds to a halfspace defined by a hyperplane.   Given a point in the intersection of the halfspaces, Qhull computes their intersection.   If you do not have an interior point, it can be computed by linear programming.   

For more information and examples, see
    http://www.qhull.org/html/qhalf.htm

Here is the Qhull identity pipeline -- from the vertices of a cube to halfspaces back to original points
     rbox c | qconvex FV n | qhalf Fp

**Comment by cbbarber** [comment]
Have you resolved this issue?  If so, please close.
