### ISSUE TITLE
Dangling pointer

### ISSUE THREAD

**Issue by mgehre** [qhull/qhull#46]
Detected by clang trunk:
```
src/libqhullcpp/RoadError.h:67:52: warning: returning address of local temporary object [-Wreturn-stack-address]
    static const char  *stringGlobalLog() { return global_log.str().c_str(); }

```
because `str()` yields a temporary `std::string`, and thus this function returns a pointer to a destroyed buffer.

See https://github.com/qhull/qhull/blob/331d567fe41170ad39c0ad0f733093b420bdbdf2/src/libqhullcpp/RoadError.h#L67

**Comment by cbbarber** [comment]
The code appears to work OK because it is expanded inline.   

For example, qhulltest/qhulltest.cpp 
        if(!RoadError::emptyGlobalLog()){
            cout << RoadError::stringGlobalLog() << endl;
            RoadError::clearGlobalLog();
    
Agreed this is poor practice.   Please recommend or post an alternative coding.   RoadError::global_log is declared as
       static std::ostringstream  global_log; //!< May be replaced with any ostream object
                                    //!< Not reentrant -- only used by RoadError::logErrorLastResort()

**Comment by mgehre** [comment]
A fix would be to replace this by `static std::string stringGlobalLog() { return global_log.str(); }`

**Comment by cbbarber** [comment]
Thanks Matthias.  It works well.   I'll add it to Qhull 2019.2 along with the other changes.

                                --Brad


At 03:26 PM 10/31/2019, Matthias Gehre wrote:

**Comment by cbbarber** [comment]
Qhull 2020.1 is available on GitHub with your recommended change.
   https://github.com/qhull/qhull/wiki

Sorry for the long delay.    Many thanks for reporting the problem.
