### ISSUE TITLE
Qhull does not compile on macOS

### ISSUE THREAD

**Issue by tschoonj** [qhull/qhull#48]
Seeing this with both the latest stable release as well as master:

```
Scanning dependencies of target qhull
[ 73%] Building C object CMakeFiles/qhull.dir/src/qhull/unix_r.c.o
[ 75%] Linking C executable qhull
ld: can't open output file for writing: qhull, errno=21 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any thoughts?

**Comment by stephanmg** [comment]
Can you provide `make VERBOSE=1` output?

**Comment by tschoonj** [comment]
```
[ 73%] Linking C executable qhull
/usr/local/Cellar/cmake/3.15.4/bin/cmake -E cmake_link_script CMakeFiles/qhull.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/qhull.dir/src/qhull/unix_r.c.o  -o qhull libqhullstatic_r.a -lm 
ld: can't open output file for writing: qhull, errno=21 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [qhull] Error 1
make[1]: *** [CMakeFiles/qhull.dir/all] Error 2
make: *** [all] Error 2
```

Perhaps ld doesn't like that the -o option is positioned between the linker objects unix_r.c.o and libqhullstatic_r.a?

**Comment by stephanmg** [comment]
IIRC, errno=21 means EISDIR on MacOS X. So, can you check, qhull seems to be a directory. Thus the file is not created.

**Comment by tschoonj** [comment]
Good catch: I think I understand why it fails: there is already a directory called Qhull, and my APFS partition is not case-sensitive (the default).

Any chance you can rename that folder? Or perhaps write the qhull executable somewhere else?

**Comment by stephanmg** [comment]
@tschoonj yes I believe this is the reason. I'm on revision from Sep 26, 2018 with commit id 33ace20 where your problem does not exist for me. So I think one of the maintainers might adjust for this issue.

**Comment by tamasmeszaros** [comment]
I've provided the pull request to fix this. It was introduced by the changes from my PR some time ago.

**Comment by stephanmg** [comment]
@tamasmeszaros great!

**Comment by cbbarber** [comment]
Pulled into Master with many thanks to tamasmeszaros and tschoonj for solving this issue.

It was also reported by C. Xu in July.
