### ISSUE TITLE
/usr/bin/ld: cannot open output file qhull: Is a directory

### ISSUE THREAD

**Issue by debinz** [qhull/qhull#52]
Hi!

I am using your great code! I have successfully config and generate the code by using cmake-3.16.0-rc4 on ubuntu 16.04, and my gcc/g++ version is 4.8.5, but when I `make` the code, errors occurred:
![image](https://user-images.githubusercontent.com/24296206/69689586-4990f700-1104-11ea-8c21-e8321618b115.png)
Can you give me some advice about that? Than you for your kind assistance!

Zeng

**Comment by cbbarber** [comment]
The 'Qhull' directory was renamed QhullExport in CMakeLists.txt.   See issue #48.  Qhull 2020.1 will include this fix.
