### ISSUE TITLE
hull vertices order

### ISSUE THREAD

**Issue by joobei** [qhull/qhull#54]
I'm passing every single pixel of an image as a point to qhull so that I can receive a 2D outline. The problem is that the order of the vertices in the hull is somewhat tied to facets? I just want to draw the hull as a continuous line but when I iterate over the output of qhull.vertexList() the vertices are in a weird order. (Left: lines drawn between subsequent vertices in QhullVertexList, Right: Input Image)

<img width="831" alt="test" src="https://user-images.githubusercontent.com/2638631/70905881-b9144b00-200d-11ea-8e87-65601aed7996.png">

Documentation says that "In 2-d, the extreme points (vertices) are listed in counterclockwise order". But that doesn't seem to be the case.
Any ideas on how to get the vertices in sequential order so that I can draw the convex hull correctly?

**Comment by cbbarber** [comment]
The problem is that QhullVertexList is defined as QhullLinkedList<QhullVertex> which makes use of the 'next' and 'previous' links in the corresponding C type 'vertexT'.    As with other linked lists in Qhull, the vertex list is reordered during hull construction for internal purposes. 

The C code of Qhull, for 2-D convex hulls, reconstructs the counterclockwise order in qh_printextremes_2d [libqhull_r/io_r.c].   Similar code would be needed for QHull::vertexList().    I'll consider it for 2020.1 but it may be pushed to a later release.   Let me know if you have implemented this code.

Many thanks for reporting the issue.  I'll update the bug list.

          --Brad

**Comment by cbbarber** [comment]
In Qhull 2020.1, nextFacet2d iterates facets and vertices in counter-clockwise order.   It is available for QhullFacet and poly2_r.c.    Qhull 2020.1 is available on github
    https://github.com/qhull/qhull/wiki

Many thanks for reporting the problem.
                  --Brad

**Comment by district10** [comment]
**sort hull vertex indexes by bearing angle**:

```cpp
// https://stackoverflow.com/questions/17074324/how-can-i-sort-two-vectors-in-the-same-way-with-criteria-that-uses-only-one-of
template <typename T, typename Compare>
std::vector<std::size_t> sort_permutation(const std::vector<T> &vec,
                                          const Compare &compare)
{
    std::vector<std::size_t> p(vec.size());
    std::iota(p.begin(), p.end(), 0);
    std::sort(p.begin(), p.end(), [&](std::size_t i, std::size_t j) {
        return compare(vec[i], vec[j]);
    });
    return p;
}
template <typename T>
std::vector<T> apply_permutation(const std::vector<T> &vec,
                                 const std::vector<std::size_t> &p)
{
    std::vector<T> sorted_vec(vec.size());
    std::transform(p.begin(), p.end(), sorted_vec.begin(),
                   [&](std::size_t i) { return vec[i]; });
    return sorted_vec;
}

std::vector<int>
convex_hull_2d(const std::vector<std::array<double, 2>> &points)
{
    RboxPoints rbox;
    Qhull qhull;
    rbox.setDimension(2);
    rbox.append(countT(2 * points.size()), (const coordT *)&points[0][0]);
    qhull.runQhull(rbox, "Fx");
    std::vector<int> indexes;
    double x = 0.0, y = 0.0;
    auto vertices = qhull.vertexList();
    for (auto &v : vertices) {
        indexes.push_back(v.point().id());
        x += points[indexes.back()][0];
        y += points[indexes.back()][1];
    }
    x /= indexes.size();
    y /= indexes.size();
    // https://github.com/qhull/qhull/issues/54
    std::vector<double> angles;
    angles.reserve(indexes.size());
    for (auto &i : indexes) {
        auto p = points[i];
        p[0] -= x;
        p[1] -= y;
        angles.push_back(std::atan2(p[1], p[0]));
    }
    return apply_permutation(
        indexes,
        sort_permutation(angles, [](double a, double b) { return a > b; }));
}
```

Hope this help.
