### ISSUE TITLE
Option to use shared linking for executables by default

### ISSUE THREAD

**Issue by StefanBruens** [qhull/qhull#57]
Currently, the executables are linked statically. It would be nice if there were an option to use dynamic linking.

https://github.com/qhull/qhull/blob/7afedcc73666e46a9f1d74632412ebecf53b1b30/CMakeLists.txt#L473-L477

**Comment by cbbarber** [comment]
Please make a suggestion on adding a CMake option for dynamic linking of the Qhull executables to CMakeLists.txt (I'm not a cmake user).

**Comment by cbbarber** [comment]
Pull request #69 is part of Qhull 2020.2.   Many thanks for your change.
