### ISSUE TITLE
ABI breakage from 2015.2 to 2019.1

### ISSUE THREAD

**Issue by roehling** [qhull/qhull#58]
Hi, 
while working on the Debian package for qhull, I ran abi-compliance-checker on the library and noticed that version 2019.1 is not binary compatible to the previously packaged version 2015.2, yet they have the same SOVERSION (7). Could you please bump the SOVERSION to avoid version conflicts?

Thanks!

**Comment by cbbarber** [comment]
Timo,
Do you have a record of what broke the ABI in 2019.1?   

Are some qhull packages released as SOVERSION 8?  If so, what is their 'dotted' version?

I'll increase the SOVERSION as requested, with a note about ABI breakage.

    --Brad

**Comment by roehling** [comment]
I have zipped the abi-compliance-checker compat reports for you:
[compat_reports.zip](https://github.com/qhull/qhull/files/4594129/compat_reports.zip)

I tried to avoid version collisions by bumping the SOVERSION to 7deb1 for a Debian release of 2019.1 (7.3.2). This way, you can release a new version with SOVERSION 8 at some point, and then the SOVERSIONS will sync up again.

**Comment by cbbarber** [comment]
Thanks Timo.  The new option for rbox, 'C,n,r,m', revealed multiple issues in Qhull.    Addressing these issues required substantial changes to merging.   There was no intent of maintaining binary compatibility.  SOVERSION should have rev'd for Qhull 2019.1. 

                --Brad


At 12:08 PM 05/07/2020, you wrote:

**Comment by cbbarber** [comment]
Hi Timo,

More questions.   Qhull has used a 3-digit VERSION (e.g., 7.3.2) and a one digit SOVERSION (e.g., 7).    

The Qhull ABI will change for almost all major and minor releases.   Should SOVERSION be an incrementing number, unrelated to VERSION? 

VERSION is major.minor.doc-change.  This roughly corresponds to Qhull's dated version "2019.1 2019/06/21".    If a documentation/unimportant change is made to a release, I'll change the release date without changing YYYY.N.

Should the Makefiles set SO to VERSION or SOVERSION?   They currently set SO to "so.$VERSION".    

VERSION and SOVERSION are primarily for Unix builds.   Should I change the numbering conventions for one or both variables?

**Comment by roehling** [comment]
In general, you should track API and ABI version numbers independently.

The most common ABI versioning is a single number that is increased whenever a structure or a function signature changes or is removed (new stuff can be added without changing the version number, because ABI versioning is only concerned with backwards compatibility, although some people disagree and increase the ABI version regardless). Similarly, the API major version is changed when something is changed or removed in the include headers such that old code might no longer compile correctly, and the minor version is changed when something new is added that does not break source code compatibility for old code.

With careful programming that avoids reordering of fields in structs and a few other gotchas, you can make the SOVERSION equal to the API major version, and it will pretty much work as you expect it.

However, if your ABI will change frequently even with minor releases, your ABI version will either need to grow faster than the API major version (it's a matter of personal taste whether you care about that), or you can use the major-minor tuple as SOVERSION (e.g., 7.3). The executable loader does not care, it treats the SOVERSION as an opaque string that is either equal (compatible) or not. The only downside is that such an SOVERSION might change even if the library technically remains binary compatible.

**Comment by cbbarber** [comment]
Thanks Timo for your explanation .  I'll change the SOVERSION for Qhull 2020.1 to "8.0" with VERSION=8.0.0

Should 'SO' in the Makefiles be "so.$(qhull_VERSION)" or "so.$(qhull_SOVERSION)"  It is currently "so.$(qhull_VERSION)".

# Define qhull_VERSION in CMakeLists.txt, Makefile, and qhull-warn.pri
# Truncated version in qhull-exports.def, qhull_p-exports.def, qhull_r-exports.def
#  libqhull_r.so -- reentrant Qhull with qh_qhT passed as an argument.
qhull_VERSION=$(shell grep 'set.qhull_VERSION ' CMakeLists.txt | grep -o '[0-9.]\+' || echo 0unknown)
qhull_SOVERSION=$(shell grep 'set.qhull_SOVERSION ' CMakeLists.txt | grep -o '[0-9]\+' || echo 0unknown)
SO  = so.$(qhull_VERSION)
...
lib/libqhull_r.$(SO): $(LIBQHULLSR_RBOX_OBJS)
	$(CC) -shared -o $@ $(CC_OPTS3) $^
	# the following line fails under MSYS, not needed for SO=dll
	-(cd lib/ && ln -f -s libqhull_r.$(SO) libqhull_r.so)
...
bin/user_eg: src/user_eg/user_eg_r.o lib/libqhull_r.$(SO)
	@echo -e '\n\n==================================================='
	@echo -e '== If user_eg fails to link on a Windows host, use'
	@echo -e '==   "make SO=dll" and copy lib/libqhull_r.dll to bin/'
	@echo -e '== Otherwise if user_eg fails to link, switch to -lqhullstatic_r'
	@echo -e '===================================================\n'
	$(CC) -o $@ $< $(CC_OPTS1) $(CC_OPTS3) -Llib -lqhull_r -lm

**Comment by roehling** [comment]
The loader uses the SONAME to find the library, so you'll need `.so.$(SOVERSION)`. You can still use the normal VERSION if you create an additional symlink with the SOVERSION, like CMake does. Some people prefer this because they like to have the full version number in the library file name.

**Comment by cbbarber** [comment]
Hi Timo,

Many thanks for your help with the Qhull builds.   Qhull 2020.1 is available on github. 
https://github.com/qhull/qhull/wiki

Let me know if you find anything else that needs changing.
                              --Brad

**Comment by roehling** [comment]
Nice! I immediately pulled the new tarball for Debian, and I'm preparing the downstream release right now. Thanks!

**Comment by cbbarber** [comment]
Hi Timo,

New issue for Qhull 2020.2 -- Inconsistent builds #77

Please take a look.  The main change is removing libqhull.so and libqhull_p.so from the CMake and DevStudio builds.

Please review the choice of 8.0.1 for the first try at Qhull 2020.2 and the proposed version of 8.0.2 for deployed Qhull 2020.2 release.    Should the version be 8.1.0?

For Qhull 2020.2, the Makefiles and documentation changed, as did the implementation of the C++ interface.   The C code did not change except for some cleanup.

**Comment by roehling** [comment]
Hi Brad,

I ran the abi-compliance-checker to compare the current Git HEAD with release 2020.2, and there's only a very minor issue in qhullcpp with the QhullPointsIterator class, but the release is still flagged as 100% binary compatible. IMHO the version number 8.0.2 is good.

**Comment by cbbarber** [comment]
Hi Timo,

Release candidate for Qhull 2020.2 is on Github with tag v8.0.2

It contains numerous changes to CMakeLists and other builds.   The primary change is consistent builds deploying libqhull_r.so.   The non-reentrant shared library is excluded from 'ALL'.

Please take a look.    Suggestions welcome.   The next release will be in a year or so.
