### ISSUE TITLE
2015.1 is missing the CMakeModules directory

### ISSUE THREAD

**Issue by niclasr** [qhull/qhull#6]
I tried to build qhull 2015.1from the tarball on www.qhull.org but cmake complained that it can't find CheckLFS.cmake. The directory CMakeModules seems to not have gone into the tarball.
Please update it.

**Comment by qhull** [comment]
Thanks Niclas for reporting the problem

The file is here
    https://github.com/qhull/qhull/blob/master/CMakeModules/CheckLFS.cmake

It will be added to the next release of Qhull (later today perhaps).

                                               --Brad

**Comment by qhull** [comment]
This was fixed in qhull-2015.2.  Many thanks for reporting the problem.

                                 --Brad

At 11:29 AM 1/18/2016, you wrote:
