### ISSUE TITLE
Broken QLinkedList::const_iterator::operator->

### ISSUE THREAD

**Issue by jmirabel** [qhull/qhull#61]
I report here a minor issue encounter while using this very useful library.

Shouldn't
https://github.com/qhull/qhull/blob/7afedcc73666e46a9f1d74632412ebecf53b1b30/src/libqhullcpp/QhullLinkedList.h#L175
be
```c++
const T *       operator->() const { return &i; } 
```
?

**Comment by cbbarber** [comment]
Yes.  This operator was broken.    I'll post the fix soon.

**Comment by jmirabel** [comment]
Thank you.
