### ISSUE TITLE
Tag for v8.0.0 or release 2020.1

### ISSUE THREAD

**Issue by nandahkrishna** [qhull/qhull#64]
I was trying to clone the repository and execute `git checkout 2020.1` or `git checkout v8.0.0`, but that doesn't work because it seems that a tag hasn't been created for `2020.1` or `8.0.0`. Is that in the process of being done?

I'm mainly asking this because I'm working on [Homebrew](https://brew.sh)'s `livecheck` feature which checks for the latest versions of packages, and `qhull`'s latest `2020.1` release wasn't getting detected.

Thank you!

**Comment by cbbarber** [comment]
They were created a week ago, but I forgot that a tag push is also required.  

Thanks for your note.
