### ISSUE TITLE
libqhull and libqhull_r mutually exclusive: intended?

### ISSUE THREAD

**Issue by SpaceIm** [qhull/qhull#75]
`libqhull` and `libqhull_r` have several similar symbols leading to ODR violation if `libqhull` and `libqhull_r` libs are both linked into the same project (for example through 2 dependencies, one depending on `libqhull` like `gdal`, and another one depending on `libqhull_r`):

```c++
extern const char qh_version[];
extern const char qh_version2[];

void    qh_exit(int exitcode);
void    qh_fprintf_stderr(int msgcode, const char *fmt, ... );
void    qh_free(void *mem);
void   *qh_malloc(size_t size);
```

Is it intended?
It might be an issue in conan package manager (https://github.com/conan-io/conan-center-index/issues/2408), because both libs are shipped together.

EDIT: I missed something, it's C, actually most functions in `qhull` and `qhull_r` lead to multiple definitions if both libs are linked :/

**Comment by cbbarber** [comment]
qhull and qhull_r are nearly identical with the exception of a qhT* first argument for qhull_r functions.   qhull uses a static global data structure qhT qh_qh, while qhull_r allocates the global data structure on the heap (qhT *).

If a package includes both qhull and qhull_r, you should report an error.   If a package requests qhull, you should report a warning.   All new users should develop code for qhull_r.   The conversion for qhull to qhull_r is straight forward but tedious.   Alternatively, legacy users can link the static libraries.

Only qhull_r should be shared.   I'll open an issue for changing CMakeLists.txt.

**Comment by SpaceIm** [comment]
Thanks for the clarification.
That's not easy to handle in package managers, since it prevents to have both in its dependency graph a library depending on qhull (GDAL depends on qhull non reentrant) and another one depending on qhull reentrant.

**Comment by cbbarber** [comment]
Qhull 2020.2 installs libqhull_r.so.  This is the reentrant library for Qhull.  Users of libqhull.so should link with libqhullstatic.a or convert to reentrant Qhull.

Github has the release candidate for 2020.2.   Once released, GDAL and other users of libqhull.so should be notified.

Thanks Spacelm for your contributions to 2020.2

                              --Brad
