### ISSUE TITLE
CMakeFiles/Makefile2:156: recipe for target 'CMakeFiles/user_eg3.dir/all' failed

### ISSUE THREAD

**Issue by debinz** [qhull/qhull#79]
HI!

Thank you for developing this awesome tool. When i built this tool on the Ubuntu 18.04 platform, i got an error:
"
Scanning dependencies of target user_eg3
[ 98%] Building CXX object CMakeFiles/user_eg3.dir/src/user_eg3/user_eg3_r.cpp.o
[100%] Linking CXX executable user_eg3
/usr/bin/ld: libqhullstatic_rd.a(global_r.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(stat_r.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(geom2_r.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(poly2_r.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(merge_r.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(libqhull_r.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(geom_r.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(poly_r.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(qset_r.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(mem_r.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(random_r.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(usermem_r.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(io_r.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(user_r.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libqhullstatic_rd.a(rboxlib_r.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
CMakeFiles/user_eg3.dir/build.make:104: recipe for target 'user_eg3' failed
make[2]: *** [user_eg3] Error 1
CMakeFiles/Makefile2:156: recipe for target 'CMakeFiles/user_eg3.dir/all' failed
make[1]: *** [CMakeFiles/user_eg3.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
"
btw, my gcc version is 4.8.5, my cmake version is 3.18.4.
I don't know how to fix it. Can you give me some advice? Any suggestions will be welcome, Thank you!

Zeng

**Comment by cbbarber** [comment]
Hi Zeng,

The rules for -fPIC are difficult to get right.   It looks like you are compling a 32-bit Qhull on a 64-bit host.    CMake is supposed to pick the right options for your machine.   You can try changing its target with the -G option.   See  README.txt
         Installing Qhull with CMake 2.6 or later

Qhull's Makefile provides more control.   It is configured for gcc but can be edited for other compilers.   The Makefile includes some additional notes on -fPIC.   Also see README.txt
        Installing Qhull on Unix with gcc

                        --Brad

At 11:19 PM 11/10/2020, debinz wrote:

**Comment by cbbarber** [comment]
No further discussion.   Closing.
