### ISSUE TITLE
tag new release?

### ISSUE THREAD

**Issue by stevengj** [qhull/qhull#97]
It's been over a year since the last release and there have been quite a few commits.  Are there any plans to tag a new release?

If you follow the [semantic versioning](https://semver.org/) spec, the next release would be 8.1, since a new backward-compatible API was added (#89).  However, since `qhull` is a longstanding project maybe you have a different versioning scheme?

**Comment by cbbarber** [comment]
The current head can be tagged as 8.1 with the understanding that I have not tested the code.  Is there a convention for this kind of tag?  Perhaps 'alpha'.  Is that OK with you and others?

The next Qhull release will hopefully be next year.  I am trying to get a large project ready for use.

**Comment by stevengj** [comment]
Yes, something like `8.1-alpha1` would be a typical pre-release tag and is compliant with the semver spec.

**Comment by cbbarber** [comment]
Will tag 8.1-alpha1.

I'll update the version names for  'qhull_VERSION' in CMakeLists.txt and 'qh_version2' in global_r.c and global.c

qhull_SOVERSION in CMakeLists.txt should also change.

Should the new SOVERSION be 

set(qhull_SOVERSION 8.1) # For SOVERSION 

or 

set(qhull_SOVERSION "8.1-alpha1") # For SOVERSION 

or something else?

**Comment by cbbarber** [comment]
Changes.txt will also change.  Here is a draft.  Any additions or corrections?

------------
Qhull 8.1-alpha1 github 2021/09/22
- tag Qhull #head for the github additions to Qhull [S.J. Johnson #97]
- testing postponed to the next release of Qhull
- global_r.c: update qh_version2
- CMakeLists.txt: update qhull_VERSION and qhull_SOVERSION

Additions to 
- accessors_r.h/.c -- Accessor functions for qhull integration [S. Johnson, B. Legat #89]

Documentation changes
- user_r.h: Replace qh_REALmax,qh_REALmin,qh_REALepsilon with REALmax,REALmin,REALepsilon in header comment
- user_r.c,user_eg2_r.c: Replace -REALmin with -REALmax in two error messages [S. Hutter #87]

- Fixed various spelling errors in code comments and Changes.txt [luzpaz #84]
- CMakeLists.txt: Change MSVC to WIN32 for [B. Nath #80]
- CMakeLists.txt: add 'BUNDLE DESTINATION' for iOS [spacelm #90]

**Comment by stevengj** [comment]
I think `SOVERSION` needs to be purely numeric for technical reasons?   (Technically, the SOVERSION doesn't even need to match the release version.)

**Comment by cbbarber** [comment]
Thanks Steve.  The value is not quoted, indicating that a numeric value is required.

I'll make the changes and tag the release this weekend.  Many thanks for your help.

                                     --Brad

At 06:45 PM 09/24/2021, Steven G. Johnson wrote:

**Comment by cbbarber** [comment]
Reopening due to kloczek #98.  Gnome does not allow '-' in version tags.

Should I tag as v8.1.alpha1 and delete tag v8.1-alpha1?

**Comment by stevengj** [comment]
I think there is some confusion here. Gnome itself doesn’t do packaging of other software, and doesn’t care what version number qhull uses. The poster in the other issue was simply suggesting that qhull should *copy* the numbering scheme used by Gnome for the Gnome software.

In contrast, semver is a widely accepted standard used by many software packages.

**Comment by cbbarber** [comment]
Will keep the tag as is.
