### ISSUE TITLE
Please make versioning packaging friendly

### ISSUE THREAD

**Issue by kloczek** [qhull/qhull#98]
Just found that `v8.1-alpha1` has been released.
It is one general issue with that versioning scheme. It is not packaging friendly.
Simple none of the packaging software allows use dashes in version strings.
I would recommend to use the same scheme which is used now in Gnome.
With that scheme is possible to use coincidence that digits are at the and of the alphabet so any version pars with non-digits on the beginning would be older than those with digits.
Using that scheme instead use `v8.1-alpha1` better would be use `v8.1.alpha1` and and than (if it will be necessary) `v8.1.beta1`, `v8.1.rc1` and at the end `v8.1.0`.
https://discourse.gnome.org/t/new-gnome-versioning-scheme/4235
With that scheme still is possible to mark that some version it is not prod version and still it is possible to package that without fiddling in version strings between versions.
Just please keep in mind that what you are producing is than consumed usually on packaging layer.

Thank you :)
(feel free to close that ticked after reading)

**Comment by stevengj** [comment]
Note that the hyphen corresponds to the semver standard: https://semver.org/

A hyphen is also supported e.g. by Debian/Ubuntu package versioning, and by RPM as I understand it. So it is not true that “no” packaging software supports this. 

Can’t Gnome just change the hyphen to a dot for its package version if hyphens aren’t supported?

**Comment by stevengj** [comment]
What packaging software doesn’t support hyphens?

**Comment by kloczek** [comment]
> A hyphen is also supported e.g. by Debian/Ubuntu package versioning, and by RPM as I understand it. So it is not true that “no” packaging software supports this. And any particular packaging system that doesn’t support semver can always omit the hyphen or change it to a dot when naming its package, no?

Similar is with rpm `~` but that is part of special treatment such cases and always requires manual intervention of the packager to add handling part which should not be part of version string.
In other words even dpkg do not accept `-` as part of the version string.

Scheme which I've described allows avoid all those hassles.

**Comment by kloczek** [comment]
> What packaging software doesn’t support hyphens?

All .. dpkg, rpm Solaris IPS, *BSD packaging software, Windows msi.

**Comment by stevengj** [comment]
http://manpages.ubuntu.com/manpages/trusty/man5/deb-version.5.html says hyphens are allowed in the upstream version

**Comment by kloczek** [comment]
As I wrote it is special feature and that part is discarded from version string.

**Comment by stevengj** [comment]
And as you wrote, RPM docs support hyphens in upstream versions as well, but recommend that the packager converts them to hyphens for RPM sorting. https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/

i.e. semver upstream versions are supported

**Comment by kloczek** [comment]
As I wrote that part after `~` is ignored as part of the version string and using it requires manual intervention.

**Comment by stevengj** [comment]
Even the document you linked about Gnome says that “individual components like Glib and Gtk typically follow the semver standard”

Whereas, as the document explains, Gnome versioning is different—and atypical—because Gnome as a whole is a combination of many software packages with their own versioning. That also makes Gnome a poor model to follow for versioning individual packages like qhull.

Whereas semver is a standard followed by many upstream packages, and as far as I can tell all of the major packaging systems have figured out how to deal with it even it means occasional renamings.

**Comment by kloczek** [comment]
Again .. evertyhing after `~` is ignored so `foo.bar~bazz` will be the same as `foo.bar~bazar`

Really you want to say that you don't see that using gnome proposed of the versioning scheme solves all issues without using special features implemented in some packaging software??

**Comment by stevengj** [comment]
semver is a widely accepted standard (used by Gnome components themselves as your own link points out).  The Gnome versioning scheme is not a standard, and the Gnome developers themselves explain why Gnome (as a whole) is an exceptional case where they can’t use semver. 

It doesn’t make sense to adopt a nonstandard ad hoc versioning scheme developed for an exceptional case when a standard is available, and when downstream packagers have already documented how to deal with upstream packages using this semver standard.

**Comment by stevengj** [comment]
The other major standard here is Python versioning (https://www.python.org/dev/peps/pep-0440/#version-scheme), which would use “8.1a1”

**Comment by cbbarber** [comment]
Let's close this issue.  There's no right answer.   

Changing a release tag is bad news for everyone who has automatically picked up the release.   It will stay as is.

This is just a tag to record a year's worth of github commits.  There will not be an 8.1 release.

Thomasz,
Thanks  for your suggestion.  I'll take it into consideration if such a tag is needed again.
                                                 --Brad

**Comment by kloczek** [comment]
> Changing a release tag is bad news for everyone who has automatically picked up the release. It will stay as is.

That was only suggestion for new tags :P 
I've not been asking to change last tag and I've pointed only that current versioning scheme has some not nice consequences which is possible to avoid altering a bit (only) that scheme.

Thx.

**Comment by stevengj** [comment]
By the way, why are some of the version numbers semver-like (e.g. 7.2.1, 8.1, …) and some of them year based (e.g. 2020.2)?   Is the intention to settle on the former in the future, or will you sometimes use year-based versions too?

**Comment by cbbarber** [comment]
The official version at qhull.org use the year and date convention (like Perforce).   Sometimes years pass between versions.  It also reminds people how far out-of-date they are.   For example meshlab is upgrading from Qhull 2003.1

Unix users requested a dotted version number, so one was instigated a while ago.   

The parallel versions will continue (i.e., two tags for each release)

                                --Brad

**Comment by stevengj** [comment]
Thanks for clarifying!
